# Generated by Django 4.1.1 on 2022-10-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='about_us')),
                ('Url', models.CharField(max_length=20000)),
                ('SMTitle', models.CharField(max_length=2000)),
                ('SMDescription', models.TextField()),
                ('SMKeywords', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-id',)},
        ),
    ]
