# Generated by Django 4.1.1 on 2022-10-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='album')),
                ('Url', models.CharField(max_length=20000)),
                ('SMTitle', models.CharField(max_length=2000)),
                ('SMDescription', models.TextField()),
                ('SMKeywords', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
