# Generated by Django 4.1.1 on 2022-10-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_album_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='album-image')),
                ('Album_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.album')),
            ],
        ),
    ]
