# Generated by Django 4.1.1 on 2022-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50)),
                ('Adress', models.TextField()),
                ('Telephone', models.CharField(max_length=15)),
                ('Mobile', models.CharField(max_length=15)),
                ('Whatsapp', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=250)),
                ('Longitude', models.CharField(max_length=30)),
                ('Latitude', models.CharField(max_length=30)),
                ('Facebook', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=50)),
                ('Linkedin', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Company')),
                ('Url', models.CharField(max_length=20000)),
                ('SMTitle', models.CharField(max_length=2000)),
                ('SMDescription', models.TextField()),
                ('SMKeywords', models.CharField(max_length=2000)),
            ],
        ),
    ]
