# Generated by Django 4.1.1 on 2022-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('Show_Price', models.BooleanField(default=False)),
                ('Actual_Price', models.IntegerField()),
                ('Offer_Price', models.IntegerField()),
                ('Show_Whatsapp', models.BooleanField(default=False)),
                ('Whatsapp_Number', models.CharField(max_length=15)),
                ('Show_Enquiry', models.BooleanField(default=False)),
                ('SMTitle', models.CharField(max_length=2000)),
                ('SMDescription', models.TextField()),
                ('SMKeywords', models.CharField(max_length=2000)),
            ],
        ),
    ]
