# Generated by Django 4.1.1 on 2022-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Show_Enquiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Show_Price',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Show_Whatsapp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
