# Generated by Django 4.1.1 on 2022-10-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_show_enquiry_alter_product_show_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('Show_Price', models.BooleanField(default=False)),
                ('Actual_Price', models.IntegerField(blank=True, null=True)),
                ('Offer_Price', models.IntegerField(blank=True, null=True)),
                ('Show_Whatsapp', models.BooleanField(default=False)),
                ('Whatsapp_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Show_Enquiry', models.BooleanField(default=False)),
                ('SMTitle', models.CharField(max_length=2000)),
                ('SMDescription', models.TextField()),
                ('SMKeywords', models.CharField(max_length=2000)),
            ],
        ),
    ]
