# Generated by Django 4.1.1 on 2022-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Actual_Price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Offer_Price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
