# Generated by Django 4.1.1 on 2022-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_service_actual_price_alter_service_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Actual_Price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Offer_Price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
