# Generated by Django 4.1.1 on 2022-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_service_actual_price_alter_service_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Show_Enquiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
