# Generated by Django 4.1.1 on 2022-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_service_show_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Actual_Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Offer_Price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Show_Enquiry',
            field=models.BooleanField(default=False),
        ),
    ]
