# Generated by Django 4.1.1 on 2022-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_product_actual_price_alter_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Actual_Price',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Offer_Price',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='SMKeywords',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='SMTitle',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Show_Enquiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Show_Price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Show_Whatsapp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Whatsapp_Number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
