# Generated by Django 4.1.1 on 2022-10-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_service_actual_price_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Twitter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
