# Generated by Django 4.1.1 on 2022-10-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_contact_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
