# Generated by Django 4.1.1 on 2022-10-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_enquiry_alter_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(),
        ),
    ]
