# Generated by Django 4.1.1 on 2022-10-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Mobile_Number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Product_Name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Refer_number',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
