# Generated by Django 4.1.1 on 2022-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_enquiry_email_enquiry_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Blog_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Image_Gallery', models.BooleanField(blank=True, default=False, null=True)),
                ('Contact_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Products_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Service_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Feedback_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Enquiry_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Group_Company', models.BooleanField(blank=True, default=False, null=True)),
                ('Testimonials', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
