# Generated by Django 4.1.1 on 2022-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_manage_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Blog_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Image_Gallery', models.BooleanField(blank=True, default=False, null=True)),
                ('Contact_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Products_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Service_Page', models.BooleanField(blank=True, default=False, null=True)),
                ('Testimonials', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
