# Generated by Django 4.1.1 on 2022-10-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_quick_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Of_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='CompanyLogo')),
            ],
        ),
    ]
