# Generated by Django 4.1.1 on 2022-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_group_of_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tes_Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Testimonial', models.TextField()),
                ('Tes_Image', models.ImageField(blank=True, null=True, upload_to='TestimonialImage')),
            ],
        ),
    ]
