# Generated by Django 4.1.1 on 2022-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('Sub_Caption', models.CharField(max_length=100)),
                ('Button_Label', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=1000)),
                ('Banner_Image', models.ImageField(blank=True, null=True, upload_to='BannerImage')),
            ],
        ),
    ]
