# Generated by Django 4.1.1 on 2022-10-28 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
