# Generated by Django 4.1.1 on 2022-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_links',
            name='Optional_Products',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quick_links',
            name='Optional_Service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
