# Generated by Django 4.1.1 on 2022-11-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_album_images_alter_contact_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='Images',
        ),
    ]
