# Generated by Django 4.1.1 on 2022-11-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_about_mission_about_vision_alter_about_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='Time',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
