# Generated by Django 4.1.1 on 2022-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_enquiry_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Url',
            field=models.CharField(max_length=20000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Url',
            field=models.CharField(max_length=20000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='Url',
            field=models.CharField(max_length=20000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='Url',
            field=models.CharField(max_length=20000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Url',
            field=models.CharField(max_length=20000, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Url',
            field=models.CharField(max_length=20000, null=True, unique=True),
        ),
    ]
