# Generated by Django 4.1.1 on 2022-11-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_product_url_service_url_alter_about_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Show_Feature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Show_Feature',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
