# Generated by Django 4.1.1 on 2022-11-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_product_show_feature_service_show_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='album_image',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-id',)},
        ),
    ]
