# Generated by Django 4.1.1 on 2022-11-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_album_options_alter_album_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
