# Generated by Django 4.1.1 on 2022-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_enquiry_address_enquiry_district_enquiry_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='District',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
