# Generated by Django 4.1.1 on 2022-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_enquiry_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
