# Generated by Django 4.1.1 on 2022-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_about_smdescription_alter_about_smkeywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
