# Generated by Django 4.1.1 on 2022-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_rename_primary_theme_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
