# Generated by Django 4.1.1 on 2022-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album_image',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banners',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group_of_companies',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
