# Generated by Django 4.1.1 on 2022-11-21 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0052_album_status_album_image_status_banners_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='about',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='about',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='album',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='album_image',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album_image',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='album_image',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banners',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='group_of_companies',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group_of_companies',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group_of_companies',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='manage_menu',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manage_menu',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manage_menu',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='manage_menu',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='quick_links',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quick_links',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quick_links',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='quick_links',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='AddedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='Ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='album',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='album_image',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='banners',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='group_of_companies',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='Status',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
