# Generated by Django 4.1.1 on 2022-11-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_delete_user_about_addedby_about_date_about_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album_image',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='banners',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group_of_companies',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manage_menu',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quick_links',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
