# Generated by Django 4.1.1 on 2022-11-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_about_status_alter_album_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='AddedBy',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='AddedBy',
        ),
    ]
