# Generated by Django 4.1.1 on 2022-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_about_editedby_about_editedip_about_edited_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(default=10),
        ),
    ]
