# Generated by Django 4.1.1 on 2022-11-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_product_discount_service_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='discount',
            new_name='Discount',
        ),
    ]
