# Generated by Django 4.1.1 on 2022-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_rename_discount_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Mission_Title',
            field=models.CharField(default='Mission', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='Vision_Title',
            field=models.CharField(default='Vision', max_length=50),
        ),
    ]
